server:
 port: 8088
 
logging:
 level:
  org.springframework: DEBUG
  
spring:  messages:    basename: messages
    
  mvc:
    pathmatch:      matching-strategy: ant-path-matcher
  
  security:
    user:
      name: username
      password: zxcv1234
      
      

### actuator      
management:
  endpoint:
    web:
      exposure:
        include: "*"